name = "group-calendar-bot"
main = "worker.js"
compatibility_date = "2025-10-20"
workers_dev = true

[vars]
# Публичные (несекретные) переменные окружения:
BOT_USERNAME = "YourBotNameWithoutAt"
PAGES_URL    = "https://your-pages.pages.dev"

[[d1_databases]]
binding = "DB"               # то же имя используется в коде
database_name = "calendar"   # имя БД в Cloudflare D1
database_id = "REPLACE_ME"   # ID вашей БД (можно убрать и привязать через Dashboard)
